
services:

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - mysql-data:/var/lib/mysql
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
 

  web: 
      build:
         context: .
      container_name: python_web
      volumes: 
        - .:/app
      environment:
        - DB_HOST=db
      ports: 
        - "8888:8888"
      command: python  /app/main.py
volumes:
  mysql-data: